FROM python:3.6-slim

RUN apt-get update && \
    apt-get install -y \
      gcc \
      vim-tiny && \
    pip install --upgrade pip

COPY . /code
WORKDIR /code
RUN  pip install -r requirements.txt

ENV FLASK_APP=/code/app.py
EXPOSE 5001

CMD uwsgi --ini uwsgi-final.ini
